source 'https://github.com/CocoaPods/Specs.git'
#use_frameworks!

platform :ios, '10.0'

target 'QYHEspBlufi_Example' do
  pod 'QYHEspBlufi', :path => '../'

  target 'QYHEspBlufi_Tests' do
    inherit! :search_paths

    
  end
end
